kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE_USERNAME-viewer
  namespace: NAMESPACE_NAME
rules:
- apiGroups: ["", "extensions", "apps","rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get","list","watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get","list","watch"]