kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE_USERNAME-user
  namespace: NAMESPACE_NAME
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts","services","replicationcontrollers","podtemplates","pods","persistentvolumes","persistentvolumeclaims","nodes","endpoints","limitranges","configmaps","componentstatuses"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get","watch","list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]